### ISSUE TITLE
Instead of (commenting inline) on the project tree. Create sections, like "site.json" has.

### ISSUE THREAD

**Issue by blzaugg** [wedeploy/electricjs.com#14]
Page: http://electricjs.com/docs/project-structure.html

![project tree](https://cloud.githubusercontent.com/assets/1626739/21827969/cf187e88-d742-11e6-9e71-f12a92a931b0.PNG)

**Comment by zenorocha** [comment]
Nice! You can also use this tool to generate a better looking file tree.

```
brew install tree
tree .
```

**Comment by zenorocha** [comment]
> See https://github.com/braziljs/conf-boilerplate#structure as reference

**Comment by zenorocha** [comment]
Fixed on https://github.com/wedeploy/electricjs.com/commit/9e149a195fe29ab3b5f2dd282d6b3d2ccde353b5

> See http://electricjs.com/docs/getting-started.html#structure
