### ISSUE TITLE
Similarly colored text is confusing

### ISSUE THREAD

**Issue by blzaugg** [wedeploy/electricjs.com#15]
![text color](https://cloud.githubusercontent.com/assets/1626739/21828145/c84abc8c-d743-11e6-8cb9-e9cc927e0396.PNG)

I overlooked the "layouts" link, because I thought it was inline code.

**Comment by zenorocha** [comment]
Fixed! Let me know what you think: 

<img width="511" alt="screen shot 2017-01-20 at 8 31 22 am" src="https://cloud.githubusercontent.com/assets/398893/22157052/dd120f90-deea-11e6-94df-8bea617e9445.png">

> http://electricjs.com/docs/getting-started.html

**Comment by blzaugg** [comment]
This looks great. Thanks!
